### ISSUE TITLE
Overpowered mid game money maker

### ISSUE THREAD

**Issue by GiornoGiobama** [Ochiona/Aurum-MC#3]
If you use a diamond miner (slimefun) in the nether to get nether quatz ore and then mine it to get topaz, it can make a LOT if money (about 620 dollars per hour considering my mining level and RNG). I think the best way to nerf it is just cut the sell price of topazs in half, because this method is still pretty risky.

**Comment by Ochiona** [comment]
Modified price from 20 to 5. This means at 64 quartz every 3 minutes, and 2 topaz per 64, you'll make not 800 but around 100 dollars per hour in the nether.
