### ISSUE TITLE
Two bugs from the new plugins installed

### ISSUE THREAD

**Issue by GiornoGiobama** [Ochiona/Aurum-MC#9]
1:Players don't have permission to use the clan plugin. (Can't create clans) 
2: The flowing lava also gives off heat. What I mean is that if you place down a lava bucket in a hole it will give you heat at a good pace but if you let the lava flow, it will give you MASSIVE amounts of heat. That means flowing lava gives the emits the same amount of heat as a source block of lava. And since the heat emission stacks, you can get from freezing to burning in 3 seconds. (Hope this made sense lol)

**Comment by Ochiona** [comment]
1. Clans has been removed.
2. Lava's spread heat is intended to be extremely hot even outside source blocks.
